# Generated by Django 6.0.1 on 2026-02-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('game', models.CharField(max_length=100)),
                ('entry_fee', models.IntegerField()),
                ('prize_pool', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tournaments/')),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
