# Generated by Django 6.0.1 on 2026-02-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_teamregistration_teamplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamregistration',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='matchschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='game',
        ),
        migrations.AlterField(
            model_name='matchschedule',
            name='room_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matchschedule',
            name='room_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(default=1, upload_to='tournaments/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_pool',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='TeamPlayer',
        ),
        migrations.DeleteModel(
            name='TeamRegistration',
        ),
    ]
