# Generated by Django 6.0.1 on 2026-02-12 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_teamregistration_teamplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamplayer',
            old_name='in_game_id',
            new_name='in_game_name',
        ),
        migrations.RenameField(
            model_name='teamregistration',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='teamregistration',
            old_name='phone',
            new_name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='game',
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='player_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='tournament',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='coreapp.tournament'),
            preserve_default=False,
        ),
    ]
