# Generated by Django 6.0.1 on 2026-02-13 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_rename_in_game_id_teamplayer_in_game_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayer',
            name='in_game_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='teamregistration',
            unique_together={('user', 'tournament')},
        ),
    ]
