# Generated by Django 6.0.1 on 2026-02-13 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_alter_teamplayer_in_game_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamregistration',
            unique_together={('user', 'tournament', 'team_name')},
        ),
    ]
