# Generated by Django 6.0.1 on 2026-02-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_alter_teamregistration_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamregistration',
            name='created_at',
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
