# Generated by Django 6.0.1 on 2026-02-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
