# Generated by Django 6.0.1 on 2026-02-16 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_delete_payment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='in_game_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.teamregistration'),
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='status',
        ),
    ]
