# Generated by Django 6.0.1 on 2026-02-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0018_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
    ]
